repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  name: aca-device-modules
  description: Open source device modules for ACAEngine
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
