inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Max: 20

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Style/IndentationWidth:
  Width: 4

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'
