inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 20

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/ParameterLists:
  Max: 4

Style/IndentationWidth:
  Width: 4

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false 
