language: ruby
rvm:
  - 2.4

before_deploy: rake doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: docs
  email: developer@acaprojects.com
  name: ACA Doc Bot
